### ISSUE TITLE
Make aggregations batch oriented

### ISSUE THREAD

**Issue by joshthoward** [trinodb/trino#10477]
Starburst has been looking into the idea of making aggregation operators batch oriented. The purpose of this issue is to share the general approach and receive community feedback and hopefully involvement. 

The steps that we currently plan to take are:
- [ ]  Introduce BatchSelectedPositions similar to SelectedPositions
- [ ] Make PagesHashStrategy batch oriented
- [ ] Make implementations of Accumulator batch oriented
- [ ] Make implementations of GroupedAccumulator batch oriented
- [ ] Make InMemoryHashAggregationBuilder batch oriented
- [ ] Make PagesHashStrategy batch oriented
- [ ] Make MultiChannelGroupByHash, BigintGroupByHash, and GroupByHash batch oriented

Some resources that we've found helpful in informing the approach:
- http://www.cs.columbia.edu/~orestis/sigmod15.pdf
- https://pure.uva.nl/ws/files/4321270/68049_09.pdf
- https://www.cs.cmu.edu/~malin199/publications/2021.filter.damon.pdf

I can update the steps above with linked issues as the discussion and implementation progresses.

**Comment by findepi** [comment]
Closing in favor of
- https://github.com/trinodb/trino/issues/14237
