### ISSUE TITLE
Table Functions support for Trino

### ISSUE THREAD

**Issue by kasiafi** [trinodb/trino#11937]
This issue serves the following purposes:
1. Decompose, prioritise and schedule the work.
2. Provide visibility into state of the task.
3. Provide a place for discussion and questions.

related issue: https://github.com/trinodb/trino/issues/1839
related PR: https://github.com/trinodb/trino/pull/11336

### Definitions
A **Table Function** is a function which returns a relation, as opposed to a scalar function which returns a single value.
A **Polymorphic Table Function (PTF)** is a Table Function which fulfils at least one of the following conditions:
- the row type of the returned table is not known at the time when the function is created
- the function takes a table as an argument, whose row type is not known when the function is created

Specifically, the output type of the Polymorphic Table Function may depend on the arbitrary table passed as an argument.

### Scope of the task
The scope of the task is to provide full support for Table Functions, including Polymorphic Table Functions.

### Subtasks
- [ ] Add language support for PTF invocation
   - [ ] grammar _(in review)_
   - [ ] AST representation _(in review)_
   - [ ] tests _(in review)_

- [ ] Add SPI support for declaring PTFs by plugins / connectors
   - [ ] The main interface: `ConnectorTableFunction` _(in review)_
      - [ ] `analyze()`: a method for _required_ and _custom_ analysis _(in review)_
      - [ ] `Analysis`: a class to provide the _required_ and _custom_ analysis results to Trino Analyzer _(in review)_
      - [ ] `InvocationHandle`: an interface for passing the _custom_ analysis results _(in review)_
      - [ ] `fulfil()`: a method to provide the function logic to Trino
   - [ ] Classes representing argument declarations, and returned type declaration _(in review)_
   - [ ] Classes representing the actual passed arguments _(in review)_
   
- [ ] Add mechanism for registering PTFs
   - [ ] Add TableFunctionRegistry with table function resolution _(in review)_
      - [ ] Prepare for path resolution when we have it _(in review)_
   - [ ] Respect differences between connector-provided and plugin-provided PTFs through separate interfaces _(in review)_
   - [ ] Add register - unregister mechanisms _(in review)_

- [ ] Analyze PTF invocation
   - [ ] scalar arguments _(in review)_
   - [ ] DESCRIPTOR arguments _(not yet supported)_
   - [ ] TABLE arguments _(not yet supported)_
   - [ ] tests
   
- [ ] Plan PTF invocation
   - [ ] Add a dedicated PlanNode: `TableFunctionNode` _(in review)_
   - [ ] Implement relevant PlanVisitors _(in review)_
   - [ ] Explain

- [ ] Execute PTF through pushdown to connector
   - [ ] Add `apply()` methods _(in review)_
   - [ ] Add `RewriteTableFunctionToTableScan` Optimizer rule _(in review)_
   - [ ] Unit test for the rule

- [ ] Add example PTF implementations: query pass-through
   - [ ] `remote_query` function for JDBC connectors: 
      - [ ] Druid _(in review)_
      - [ ] MemSql _(in review)_ 
      - [ ] MySql _(in review)_
      - [ ] Oracle _(in review)_
      - [ ] PostgreSql _(in review)_
      - [ ] Redshift _(in review)_
      - [ ] SqlServer _(in review)_
   - [ ] `remote_query` function for Elasticsearch connector _(in review)_
   - [ ] tests

### Achieved functionality
Currently, any PTF can be supported, which can be entirely realised by a connector. The connector can "capture" the PTF invocation, and replace it with a ConnectorTableHandle, which represents the PTF result.

### Following work
To provide full support for PTF, as in SQL standard, we need to:
- [ ] Support TABLE arguments (starting from the Analyzer)
- [ ] Support DESCRIPTOR arguments (starting from the Analyzer)
- [ ] EXPLAIN: think of rendering TABLE arguments, which are both _function arguments_, and _PlanNode sources_
- [ ] Support optimizations of plans involving `TableFunctionNode`: column pruning, etc
- [ ] Implement COPARTITION as JOIN
- [ ] Choose distribution of sources, regarding size, number of sources, and row/set semantics (see: DetermineJoinDistributionType)
- [ ] Handle `TableFunctionNode` in AddExchanges / AddLocalExchanges: realise the partitioning and ordering of input tables respecting their actual properties. Also, consider the output properties of `TableFunctionNode`.
- [ ] Figure out the interfaces between the PTF logic (the `fulfil()` method), and the Operator: in what form data will be provided to the PTF logic, and in what form the results will be returned to the Operator
- [ ] Add the Operator:
   - [ ] arbitrary number of sources: 0 to n
   - [ ] final partitioning and sorting of the sources (see: WindowOperator)
   - [ ] invoking the PTF logic on _cartesian product_ of the partitions from all the sources (see: Nested Loops for implementation choices)
   - [ ] appending the pass-through columns and the partitioning columns from the source tables

**Comment by kasiafi** [comment]
Closing in favor of https://github.com/trinodb/trino/issues/1839
