### ISSUE TITLE
Delta Lake: Writer version 4 support

### ISSUE THREAD

**Issue by alexjo2144** [trinodb/trino#12637]
See https://github.com/delta-io/delta/blob/master/PROTOCOL.md#writer-version-requirements

Version 4 requirements:

- [x] Support writing to the Delta Lake [Change Data Feed](https://docs.databricks.com/delta/delta-change-data-feed.html)
  - [x] https://github.com/trinodb/trino/pull/15453
- [x] Fail writes to tables that have Generated Columns [#14513](https://github.com/trinodb/trino/pull/14513)
- [x] Ensure metadata operations (add column, set comment, etc) retain generated column and CDC information [#14629](https://github.com/trinodb/trino/pull/14629)
- [x] `VACUUM` must be aware of the files created by the change data feed [#14590](https://github.com/trinodb/trino/pull/14590)
- [ ] (Optional) Support [Generated Columns](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#generated-columns)

**Comment by SanthoshPrasad** [comment]
Hi @alexjo2144 , do you have any information on when we are planning to make this change? , we are currently evaluating Trino for writes to delta using recently released MERGE support, but for our use case we need CDF and Generated Columns which are available from writer version 4.

**Comment by alexjo2144** [comment]
Hey @SanthoshPrasad , the team I work with at Starburst is planning on starting work on CDF in the next few weeks. I'll have a better idea of how long that'll take us when we actually get going on it.

Generated column support is a little trickier because we don't have a good way of converting Spark expressions into Trino expressions. In theory, any Spark expression could be used to generate the values of a GC and while some of those expressions will evaluate fine as is in Trino, some won't. 

Would you be able to share the details of how you use Generated Columns?
(cc: @claudiusli)

**Comment by ebyhr** [comment]
> VACUUM must be aware of the files created by the change data feed

I couldn't find the expected behavior (remove or ignore files in `_change_data` directory) in the protocol page. Databricks 10.4 LTS removes the directory as far as I confirmed.

**Comment by SanthoshPrasad** [comment]
@ebyhr as per  https://docs.delta.io/2.0.0/delta-change-data-feed.html#change-data-storage , the files needs to be deleted?

**Comment by SanthoshPrasad** [comment]
> Would you be able to share the details of how you use Generated Columns?

@alexjo2144 , we will be using generated columns for partitioning , most of our table have event time stamps,  and we will be querying these tables based on date range , so for optimal performance we will be having partitioning on columns like YEAR, WEEK,MONTH which are generated columns  based on event time stamp column.

**Comment by findepi** [comment]
So you not only need support for generated columns, but you also want to be able to derive predicates on them from predicate on base columns.
This is reasonable, but also not that simple. cc @claudiusli 

@SanthoshPrasad did you try using Iceberg for this use-case? Iceberg defines partitioning transforms. They are more constrained (no arbitrary expressions), but do exactly what you want, and also come with predicate derivatives builtin.

**Comment by SanthoshPrasad** [comment]
>  did you try using Iceberg for this use-case? Iceberg defines partitioning transforms. They are more constrained (no arbitrary expressions), but do exactly what you want, and also come with predicate derivatives builtin.

Delta being used by multiple applications in the organization, we are just one of the consumers.

**Comment by alexjo2144** [comment]
> I couldn't find the expected behavior (remove or ignore files in _change_data directory) in the protocol page. Databricks 10.4 LTS removes the directory as far as I confirmed.

For a first stab at it, I think it would be fine to just make sure that the files in the change data feed are always left in place when you vacuum a table in Trino. The better behavior, I think, would be to follow the Databricks semantics described [here](https://docs.databricks.com/spark/latest/spark-sql/language-manual/delta-vacuum.html#vacuum-a-delta-table-delta-lake-on-databricks):

```
...data files that are no longer in the latest state of the transaction log for the table and are older than a retention threshold [are deleted]
```

> you also want to be able to derive predicates on them from predicate on base columns.

Generated columns are populated at write time, once the data files are created they have physical columns populated with the generated values. Pushing down predicates on them should be treated just like normal columns.

> we will be having partitioning on columns like YEAR, WEEK,MONTH which are generated columns based on event time stamp column.

Starting with support for timestamp transformations like this seems like a good place to start, and mirrors the Iceberg functionality pretty nicely. Thanks for the info

**Comment by ebyhr** [comment]
Assigned @homar since he is working on the remaining CDF task.

**Comment by alexjo2144** [comment]
A document comparing the Iceberg and Delta Lake CDC implementations and how I think we should reconcile the differences is [here](https://docs.google.com/document/d/1e71DP0b9-NCecEqizgf22gJcGzOocnn2vGEZ_RTWmc4/edit?usp=sharing).

**Comment by ebyhr** [comment]
Going to close this issue as we already implemented the major items. Let's file a separated issue if necessary.
