### ISSUE TITLE
Dynamic catalogs

### ISSUE THREAD

**Issue by dain** [trinodb/trino#12709]
# Goal

Add support for adding and removing catalogs without restarting servers or interrupting existing queries.  This will be dependent on the connector being updated to support concurrent versions with same name (e.g., no JMX names containing just a catalog name). For non-compliant connectors, support a basic model where queries are killed when dropping.

For catalog properties the current plan is to simply use the existing `Map<String, String>` of arbitrary properties instead of requiring pre-declaration of typed catalog properties like is done for session and table properties.  This is mainly for expedience and backwards compatibility of the existing connector configuration system.

# MVP Plan

- [ ] Refactor Trino to supporting adding and removing catalog services cleanly
- [ ] Support distributing catalogs from coordinator to workers
- [ ] Support basic catalog shutdown on workers (e.g., keep newest catalog on workers and shutdown others)
- [ ] Add CREATE and DROP CATALOG commands
- [ ] Backwards compatible file-based catalog store
- [ ] Add permissions checks for CREATE and DROP CATALOG
- [ ] Add GRANT/DENY/REVOKE/SHOW for catalog permissions
- [ ] Support for "broken" catalogs that will not start when Trino process starts
- [ ] Support non-compliant connectors (e.g., kill queries on drop)

# Follow-up Items

- [ ] Update connectors to support concurrent versions (this item will need to be split later)
- [ ] Update UI and query history to include catalog version
- [ ] Add ALTER CATALOG commands to change name, properties and owner with security checks
- [ ] Add COMMENT ON CATALOG with security check
- [ ] Add CREATE CATALOG LIKE with security check
- [ ] Add system to identify security sensitive catalog properties
- [ ] Add SHOW CREATE CATALOG
- [ ] SPI for catalog storage

**Comment by dain** [comment]
I have a prototype if the basic stuff working, and an working on cleaning this up for submission.

**Comment by kyo-tom** [comment]
Sounds cool, the main question is how do we fix the memory leak caused by deleting the catalog

**Comment by jiangjialiang918** [comment]
Are you considering supporting password and permission authentication in HTTP mode

**Comment by Unclecc** [comment]
Hi, I use this PR to test DynamicCatalog, However, I ran into a problem when I deleted and then created a Hive Catalog. The following error occurred.
java.lang.ClassCastException: class io.trino.plugin.hive.HiveTableHandle cannot be cast to class io.trino.plugin.hive.HiveTableHandle (io.trino.plugin.hive.HiveTableHandle is in unnamed module of loader io.trino.server.PluginClassLoader @408b024e; io.trino.plugin.hive.HiveTableHandle is in unnamed module of loader io.trino.server.PluginClassLoader @aa6aca3)
	at io.trino.plugin.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:150)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:49)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:62)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:308)
	at io.trino.operator.Driver.processInternal(Driver.java:411)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:314)
	at io.trino.operator.Driver.tryWithLock(Driver.java:706)
	at io.trino.operator.Driver.process(Driver.java:306)
	at io.trino.operator.Driver.processForDuration(Driver.java:277)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:739)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:515)
	at io.trino.$gen.Trino_400_100_gc6901d5_dirty____20221025_085036_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
if you have some suggestions, please help

**Comment by leeyh0216** [comment]
Hi, @dain , @Unclecc .

I am also interested in Dynamic Catalog, so I am trying to implement my own based on the PR.
The above issue that @Unclecc mentioned was reproduced in the same way, but I thought that the issue you mentioned is not the problem.

I solved the problem by slightly modifying AbstractTypedJacksonModule .
Since the AsPropertyTypeDeserializer object caches the class loader for the class parsed once, the second call process does not use the class loader changed during the Dynamic Catalog application process, but the existing class loader is used.
Since it was for simple test purposes, I changed the method to create an AsPropertyTypeDeserializer object every time as shown below, and confirmed that it works.

```
    private static class InternalTypeDeserializer<T>
            extends StdDeserializer<T>
    {
        private JavaType bt;
        private TypeIdResolver typeIdResolver;

        private Class<T> baseClass;
        public InternalTypeDeserializer(Class<T> baseClass, TypeIdResolver typeIdResolver)
        {
            super(baseClass);
            this.bt = TypeFactory.defaultInstance().constructType(baseClass);
            this.typeIdResolver = typeIdResolver;
            this.baseClass = baseClass;
        }

        @SuppressWarnings("unchecked")
        @Override
        public T deserialize(JsonParser jsonParser, DeserializationContext deserializationContext)
                throws IOException
        {
            TypeDeserializer typeDeserializer = new AsPropertyTypeDeserializer(
                    TypeFactory.defaultInstance().constructType(baseClass),
                    typeIdResolver,
                    TYPE_PROPERTY,
                    false,
                    null);
            return (T) typeDeserializer.deserializeTypedFromAny(jsonParser, deserializationContext);
        }
    }
```

@Unclecc , If you apply the above code and test it, I think it will work.
@dain , If you have the same problem, I hope the above solution helps.

I'm not good at English... Please understand if the context is strange.

**Comment by Unclecc** [comment]
您的邮件已经收到。我会尽快处理。

**Comment by Gqyanxin** [comment]
Hi, I am also interested in Dynamic Catalog.When will this feature be available?

**Comment by bitsondatadev** [comment]
Hey @Gqyanxin and anyone else that stumbles upon this issue. Keep in mind that this is an open-source project and some of this work has to happen during the developers' free time.

The best you can do is follow this issue and the related to get a sense of how close they are.

To get a sense of why this issue may take some time, see the [discussion on this during the Trino Summit](https://youtu.be/mUq_h3oArp4?t=1175). If Dain has an update on when to expect this, he will provide them here.

**Comment by cdrappier** [comment]
Hi,

At ForePaaS, we are currently testing this new feature, which is proving to be very helpful for our use case. I have start some work on a JdbcCatalogStore inspirated by the FileCatalogStore. If this is something that is relevant to the main Trino open source project, I will create a merge request as soon as possible to discuss the subject with you.
Is that something referring to you follow-up items : SPI for catalog storage ?

My goal is to have a dynamic catalog, with persistant data, but without directly using disk.
Thanks,

**Comment by bitsondatadev** [comment]
@dain ^^

**Comment by Smith-Cruise** [comment]
What's grammar now, I want to have a test for it.

**Comment by ockhamlabs** [comment]
@dain  Any update on when the pending items for MVP will be done? We have been eagerly waiting for this to be finished for a usable dynamic catalog capability. Pl let us know

**Comment by hackeryang** [comment]
> @dain Any update on when the pending items for MVP will be done? We have been eagerly waiting for this to be finished for a usable dynamic catalog capability. Pl let us know

Our community may still need some time to complete this splendid feature, if you need this ability immediately, you can refer to the design of `HUAWEI OpenLooKeng`(which is also originated from Trino before), and backport the relevant source codes into your private trino project:  
https://github.com/openlookeng/hetu-core/blob/master/hetu-docs/en/admin/dynamic-catalog.md

**Comment by hashhar** [comment]
There is related work ongoing in https://github.com/trinodb/trino/issues/15921 - without that while you can have dynamic catalogs one of the most important connectors - Hive (and Iceberg) won't be able to be used with it.

**Comment by sarlaccpit** [comment]
> > @dain Any update on when the pending items for MVP will be done? We have been eagerly waiting for this to be finished for a usable dynamic catalog capability. Pl let us know
> 
> Our community may still need some time to complete this splendid feature, if you need this ability immediately, you can refer to the design of `HUAWEI OpenLooKeng`(which is also originated from Trino before), and backport the relevant source codes into your private trino project: https://github.com/openlookeng/hetu-core/blob/master/hetu-docs/en/admin/dynamic-catalog.md

Where can I find more information about the different types of shared filesystems that this feature could work with.  The documentation above mentions `fs.client.type=hdfs` as an example.  I'm interested to learn what other options would exist.  And in Kubernetes context, if the shared volumes could be arbitrary PersistentVolumeClaims mounted in?

**Comment by hackeryang** [comment]
> > > @dain Any update on when the pending items for MVP will be done? We have been eagerly waiting for this to be finished for a usable dynamic catalog capability. Pl let us know
> > 
> > 
> > Our community may still need some time to complete this splendid feature, if you need this ability immediately, you can refer to the design of `HUAWEI OpenLooKeng`(which is also originated from Trino before), and backport the relevant source codes into your private trino project: https://github.com/openlookeng/hetu-core/blob/master/hetu-docs/en/admin/dynamic-catalog.md
> 
> Where can I find more information about the different types of shared filesystems that this feature could work with. The documentation above mentions `fs.client.type=hdfs` as an example. I'm interested to learn what other options would exist. And in Kubernetes context, if the shared volumes could be arbitrary PersistentVolumeClaims mounted in?

It seems that it only support `HDFS` and `local file` for now:  
https://github.com/openlookeng/hetu-core/blob/master/hetu-docs/en/admin/properties.md  
https://github.com/openlookeng/hetu-core/blob/master/hetu-docs/en/develop/filesystem.md  
I think that maybe k8s pods can use shared volumes mounted from physical hosts if you configured 'fs.client.type=local', but it wasn't tested a lot.

**Comment by xuhaiL** [comment]
i need this feature，it can be used？

**Comment by Unclecc** [comment]
您的邮件已经收到。我会尽快处理。

**Comment by dungdm93** [comment]
It's useful to implementation k8s CRD based catalogs. And further more is Trino k8s operator.

**Comment by Unclecc** [comment]
您的邮件已经收到。我会尽快处理。

**Comment by gmartini2019** [comment]
Hey, did you guys figure out the dynamic catalog? I am trying to make an API just for that, but I am missing the specific user permission that will allow me to do so.

**Comment by Unclecc** [comment]
您的邮件已经收到。我会尽快处理。

**Comment by hashhar** [comment]
@dain A question, the `CatalogVersion` javadoc says:

```
/**
 * Version of a catalog.  The string maybe compared lexicographically using ASCII, and to determine which catalog version is newer.
 */
```

Right now none of the implementations actually adhere to this though and nor do we use `CatalogVersion#compareTo` anywhere.

e.g. in `FileCatalogStore#computeCatalogVersion` we break the contract by returning a length-prefixed hash of catalog name, connector name and properties. We also have a javadoc there which says:

```
/**
 * This is not a generic, universal, or stable version computation, and can and will change from version to version without warning.
 * For places that need a long term stable version, do not use this code.
 */
```

This is interesting because the `CatalogStore` interface always returns the "latest" version of the catalog (because concurrency is being limited in `CatalogDynamicCatalogManager` usign the `catalogsUpdateLock` which means the `CatalogVersion` is of no use for doing things like optimistic concurrency control in a database-backed catalog store for example.

This is confusing. Can you please clarify whether `CatalogVersion` is something which the `CatalogStore` implementation should care about? If not maybe we should move that computation to the `CatalogManager`.

Also lot of SPIs around pluggable catalog stores are marked `@Experimental` at the moment. Do you think it's time to promote them to be stable?

**Comment by Unclecc** [comment]
您的邮件已经收到。我会尽快处理。

**Comment by hashhar** [comment]
In an offline discussion we realised that the `CatalogVersion` contract doesn't need to define lexicographic ordering because in current implementation the engine or catalog store never needs a sorting of catalog versions - only the latest catalog version and using the catalog version to disambiguate the catalog handles for the same connector with same catalog name.

I'll send a PR with the javadoc updates and some code cleanup.

**Comment by RoeyoOgen** [comment]
Hi all, 
I see in the docs that "This feature is experimental only. Because of the security implications the syntax might change and be backward incompatible."

But i can't seem to find a list of implications, is there one?

Also, is any help needed to make this project fully robust and not "experimental"?

**Comment by Unclecc** [comment]
您的邮件已经收到。我会尽快处理。

**Comment by sopel39** [comment]
I think dynamic catalogs would be especially useful in agentic workloads, e.g: with MCP endpoints providing catalog maintenance for non tech users.

**Comment by Unclecc** [comment]
您的邮件已经收到。我会尽快处理。

**Comment by findepi** [comment]
Trino now has Dynamic Catalogs. Of course there are follow-up issues, and these are tracked separately.
This roadmap issue is not being kept up to date as a way to organize future work on Dynamic Catalogs.

Good job, everyone involved. 👏

**Comment by Unclecc** [comment]
您的邮件已经收到。我会尽快处理。
