### ISSUE TITLE
[JDK 21] Build and run Trino on JDK 21

### ISSUE THREAD

**Issue by wendigo** [trinodb/trino#17017]
Known problems:

- [x] `extra-enforcer-rules` does not recognize JDK 21 with the `enforceBytecodeVersion` rule (when `project.build.targetJdk` is set to `21`)
    - https://github.com/mojohaus/extra-enforcer-rules/pull/262 https://github.com/airlift/airbase/pull/360
- [x] `maven-dependency-plugin` cannot read JDK 21 classes `Unsupported class file major version 65` (old ASM is used)
	- updating plugin ASM dependency works  https://github.com/airlift/airbase/pull/359 
- [x] `modernizer-maven-plugin` cannot read JDK 21 classes `Unsupported class file major version 65` (old ASM is used)
	- updating plugin ASM dependency works  https://github.com/airlift/airbase/pull/359
- [x] `maven-shade-plugin` cannot shade JDK 21 classes
	- updating plugin ASM dependency works  https://github.com/airlift/airbase/pull/359
- [x] `guice` is shading outdated ASM 
- [ ] [replace synchronized methods and blocks with locks usage](https://github.com/trinodb/trino/issues/17045)
- [ ] refactor managed classes that are accepting ThreadPoolExecutors (JMX)
- [ ] update `Airlift` to use Virtual Threads for `jetty-client` and `jetty-server`
- [x] update error-prone to version supporting JDK 21 (https://github.com/google/error-prone/issues/3843 & https://github.com/typetools/checker-framework/issues/5672)
- [x] fix/update ignite to include fix for https://github.com/apache/ignite/issues/10720 (https://github.com/apache/ignite/pull/10764#issuecomment-1576905327)
- [ ] update PMD in airbase to a version that works unders 21 (https://github.com/pmd/pmd/issues/4583)
- [x] https://github.com/trinodb/trino/pull/18797
- [x] https://github.com/trinodb/trino/pull/18796

**Comment by wendigo** [comment]
I've been able to compile and run Trino with mentioned changes on JDK 21:

```
❯ docker run trino:413-SNAPSHOT-arm64
+ launcher_opts=(--etc-dir /etc/trino)
+ grep -s -q node.id /etc/trino/node.properties
+ launcher_opts+=("-Dnode.id=${HOSTNAME}")
+ exec /usr/lib/trino/bin/launcher run --etc-dir /etc/trino -Dnode.id=f553225d9acc
OpenJDK 64-Bit Server VM warning: Ignoring option G1UsePreventiveGC; support was removed in 21.0
WARNING: Support for the ARM architecture is experimental
# WARNING: Unable to attach Serviceability Agent. You can try again with escalated privileges. Two options: a) use -Djol.tryWithSudo=true to try with sudo; b) echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
Apr 13, 2023 10:41:20 AM io.airlift.log.Logger info
INFO: Java version: 21-ea
```

Querying TPCH works just fine :)

**Comment by wendigo** [comment]
`https://github.com/apache/maven-dependency-analyzer` was already upgraded to ASM 9.5 and released so I assume that it will soon land in `maven-dependency-plugin`

**Comment by chenjian2664** [comment]
OMG, JDK21 is available 😱

**Comment by chenjian2664** [comment]
@wendigo So cool

**Comment by wendigo** [comment]
Related: https://github.com/trinodb/trino/pull/17044

**Comment by wendigo** [comment]
https://github.com/trinodb/trino/pull/17484

**Comment by wendigo** [comment]
https://github.com/airlift/airbase/pull/359 fixes maven plugins compatibility

**Comment by wendigo** [comment]
I've just verified that error-prone HEAD works fine with JDK 21 after https://github.com/google/error-prone/pull/3918

**Comment by wendigo** [comment]
https://github.com/airlift/airbase/pull/359

**Comment by wendigo** [comment]
https://github.com/trinodb/trino/pull/17740

**Comment by wendigo** [comment]
```
diff --git a/pom.xml b/pom.xml
index 3e6fdb8d73..e01e285d30 100644
--- a/pom.xml
+++ b/pom.xml
@@ -60,7 +60,7 @@
         <dep.drift.version>1.14</dep.drift.version>
         <dep.tempto.version>196</dep.tempto.version>
         <dep.gcs.version>2.2.8</dep.gcs.version>
-        <dep.errorprone.version>2.19.1</dep.errorprone.version>
+        <dep.errorprone.version>HEAD-SNAPSHOT</dep.errorprone.version>
         <dep.testcontainers.version>1.18.3</dep.testcontainers.version>
         <dep.duct-tape.version>1.0.8</dep.duct-tape.version>
         <dep.coral.version>2.0.153</dep.coral.version>
@@ -206,6 +206,19 @@
         <module>testing/trino-tests</module>
     </modules>

+    <repositories>
+        <repository>
+            <id>oss.sonatype.org-snapshot</id>
+            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
+            <releases>
+                <enabled>false</enabled>
+            </releases>
+            <snapshots>
+                <enabled>true</enabled>
+            </snapshots>
+        </repository>
+    </repositories>
+
     <dependencyManagement>
         <dependencies>
             <!-- Trino -->
@@ -2074,6 +2087,7 @@
                                     <exclude>com.google.guava:guava</exclude>
                                     <exclude>com.fasterxml.jackson.core:jackson-core</exclude>
                                     <exclude>com.google.j2objc:j2objc-annotations</exclude>
+                                    <exclude>com.google.errorprone:error_prone_annotations</exclude>
                                 </excludes>
                             </requireUpperBoundDeps>
                             <bannedDependencies>
```

error-prone HEAD-SNAPSHOT is working with jdk 21

**Comment by wendigo** [comment]
https://github.com/trinodb/trino/pull/17770

**Comment by wendigo** [comment]
https://github.com/google/error-prone/releases/tag/v2.20.0

**Comment by wendigo** [comment]
https://github.com/trinodb/trino/pull/17941

**Comment by wendigo** [comment]
Blocked by https://github.com/trinodb/trino/issues/18272 (it's a regression starting with JDK 20)

**Comment by wendigo** [comment]
Requires https://github.com/trinodb/trino/pull/18931 (dropping HDP2.6 images which are based on Centos6 shipped with old glibc. This prevents installing Temurin JDK 21 and other builds)

**Comment by mosabua** [comment]
Trino 432 now uses Java 21 in the Trino Docker image.

**Comment by mosabua** [comment]
The 0.14.0 release of the Trino Helm charts https://github.com/trinodb/charts now uses Trino 432 and therefore Java 21.

**Comment by mosabua** [comment]
The blog post https://trino.io/blog/2023/11/03/java-21 announces our plans to require Java 21 and asks for feedback and testing reports.

**Comment by mosabua** [comment]
https://www.linkedin.com/feed/update/urn:li:activity:7126324119733686272
