### ISSUE TITLE
Migrate Hudi connector to use TrinoFileSystem

### ISSUE THREAD

**Issue by codope** [trinodb/trino#17228]
```[tasklist]
### Tasks
- [x] Remove usages of `FileStatus`
- [x] Remove usages of `Path`
- [ ] Replace usages of `FileSystem` and `Configuration` by `TrinoFileSystem` and `HdfsConfiguration`
```
Relates to https://github.com/trinodb/trino/issues/15921

**Comment by homar** [comment]
I think this is done in scope of https://github.com/trinodb/trino/pull/17392/files
