### ISSUE TITLE
Support complex connector expression filter pushdown in mongodb

### ISSUE THREAD

**Issue by krvikash** [trinodb/trino#18513]
Complex connector expression filter pushdown in MongoDB

```[tasklist]
### Tasks
- [ ]  #18382
- [ ] #18367
- [ ] Add more Rewrite rules for complex filter expression pushdown in mongodb
- [ ] Support json_extract_scalar filter expression pushdown in mongodb
- [ ] Support from_iso8601_timestamp and from_iso8601_date filter expression pushdown in mongodb
```
