### ISSUE TITLE
Add Druid connector

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#1855]
- [x] first version of Druid connector  (https://github.com/prestosql/presto/pull/3522)
- [x] documentation (https://github.com/prestosql/presto/issues/4110)
- [x] full `AbstractTestIntegrationSmokeTest` for Druid (https://github.com/prestosql/presto/issues/4116)
- [ ] Aggregation pushdown for Druid (https://github.com/prestosql/presto/issues/4109, https://github.com/prestosql/presto/issues/4111)

**Comment by Parth-Brahmbhatt** [comment]
We are interested in this work , let us know when the connector APIs are updated to expose aggregte pushdown and we can help with this development.

**Comment by kokosing** [comment]
How about adding druid connector that does not yet support aggregation pushdown? Then we could only focus on aggregation pushdown which itself could be non trivial to do.

**Comment by findepi** [comment]
@Parth-Brahmbhatt @kokosing see discussion @ https://prestosql.slack.com/archives/CHD6386E4/p1571816266008200

**Comment by asartawi** [comment]
@findepi Thanks for the good work, what is holding this from being released?

**Comment by findepi** [comment]
Initial version of Druid connector (#3522) is merged.

**Comment by antonioromero-pm** [comment]
> We are interested in this work , let us know when the connector APIs are updated to expose aggregte pushdown and we can help with this development.

Aggregation pushdown has been added to Trino as of last quarter.

**Comment by Parth-Brahmbhatt** [comment]
> > We are interested in this work , let us know when the connector APIs are updated to expose aggregte pushdown and we can help with this development.
> 
> Aggregation pushdown has been added to Trino as of last quarter. Connectors can be updated to take advantage of it. @Parth-Brahmbhatt FYI.

@antonioromero-pm the PR to handle this in druid has been out https://github.com/trinodb/trino/pull/4313 but I just haven't found time to address some of the comments as I moved on to other things. I thought someone from Starburst was going to take over that PR but may be they also haven't found time yet. I will check back once I can carve out some time and try and address the comments so we can actually get this merged in.

**Comment by jerryleooo** [comment]
Do we have a plan to support push down [filtering during aggregation](https://trino.io/docs/current/functions/aggregate.html#filtering-during-aggregation) (["filtered aggregator"](https://druid.apache.org/docs/latest/querying/sql.html#aggregation-functions) in Druid) ?

**Comment by jerryleooo** [comment]
Also, is JOIN pushdown supported? The [Druid lookups](https://druid.apache.org/docs/latest/querying/lookups.html) may need it
