### ISSUE TITLE
Allow creating views with properties

### ISSUE THREAD

**Issue by Praveen2112** [trinodb/trino#20992]
# Background and Motivation

Currently Tables and Materialized Views has an option to provide properties as a part of its definition, we would like to extend the same to Views as well. The proposed syntax would be 

```
CREATE VIEW view_name WITH (property_key = 'property_value') AS SELECT ...
```

# Implementation details

On the implementation side - we have two options 
1. Maintain the view properties as a part of `ConnectorViewDefinition` - like `ConnectorTableMetadata` 
2. Handle a different set of APIs specific like we do for MaterializedViews like `getMaterializedViewProperties`.

Which option could we consider ?

```[tasklist]
### Tasks
- [ ] Add support for creating views in Trino Grammar. 
- [ ] Add extra_properties for Hive views like https://github.com/trinodb/trino/pull/17172
- [ ] Expose the properties via System table
- [ ] Add support to update the view properties
```

**Comment by Praveen2112** [comment]
@martint Can you please confirm the proposed syntax. 

cc: @findepi / @findinpath On how could we extend them to other connectors like iceberg or delta lake
