### ISSUE TITLE
Modernize the trino webapp

### ISSUE THREAD

**Issue by koszti** [trinodb/trino#22697]
Currently, the Trino web UI uses outdated components like react 16, jquery, and bootstrap 3. It would be great to have a fresh look and feel with more recent tooling and UI frameworks. The trino gateway for example is using vite.js with recent deps, and perhaps it would be beneficial for the trino web UI to use it as well to maintain consistency. Additionally, we could consider using a UI component library like ant design instead of plain bootstrap CSS.

Original slack thread: https://trinodb.slack.com/archives/CKCEWGYT0/p1720904086284609

**Comment by mosabua** [comment]
fyi @ytwp  ;-)

**Comment by koszti** [comment]
Potential tasks that need to be done. (Not finalized or reviewed)

**General**
- [x] Build and packaging: #22783
- [x] Decide on frontend component library: [Semi Design](https://semi.design/en-US/) (trino-gateway) or [Material UI](https://ant.design/) (trino website and documentation)
- [x] Common layout: #22869
- [x] Adjust colors, theming, and overall look and feel to follow the Trino website, see https://trino.io/ and https://trinodb.github.io/presentations/presentations/introduction/index.html#/3
- [x] Client API class with helper async `GET` and `POST` requests to the server.
- [x] Login screens and authentication: #23230

**Pages/ Components**
- [x] Cluster Overview - https://github.com/trinodb/trino/pull/23600
- [x] Query Details - https://github.com/trinodb/trino/pull/24972
- [x] Worker List - https://github.com/trinodb/trino/pull/24741
- [x] Worker Overview - https://github.com/trinodb/trino/pull/24741
- [x] Query Details - Overview - https://github.com/trinodb/trino/pull/25554
- [x] Query Details - Live Plan - https://github.com/trinodb/trino/pull/26392
- [x] Query Details - Stage Performance - https://github.com/trinodb/trino/pull/26610 and https://github.com/trinodb/trino/pull/26638
- [x] Query Details - Splits - https://github.com/trinodb/trino/pull/26654
- [x] Query Details - JSON - https://github.com/trinodb/trino/pull/26319
- [x] Query Details - References - https://github.com/trinodb/trino/pull/26327

**Comment by mosabua** [comment]
I am adding this to the roadmap since I think there is significant interest and effort. I will try to monitor and probably organize some more collaboration.

**Comment by mosabua** [comment]
@koszti I added a task to adjust the theme and colors to get aligned with the Trino website and colors, I added links to https://trinodb.github.io/presentations/presentations/introduction/index.html#/3 and the website, if you have any need for further colors or questions please reach out to myself and potentially also @aliloney .. also if we need adjusted images of the trino logo or Commmander Bun Bun we can make that happen as well

**Comment by mosabua** [comment]
First preview shipped with Trino 454

Docs are available at https://trino.io/docs/current/admin/preview-web-interface.html

**Comment by mosabua** [comment]
Also note for any client protocol stuff we should use https://github.com/trinodb/trino-js-client cc @regadas

**Comment by sajjoseph** [comment]
@mosabua and @koszti ,
To me, the new UI is fully working and nearly all the features from the legacy UI is in (the last PR waiting to be merged is #27712). 
How about adding a configuration flag that allows to swap the primary UI?  
I still prefer the large fonts on legacy UI. Is there a way we can tune it further?

**Comment by koszti** [comment]
Since we’ve reached feature parity here is a potential roadmap to make the Preview UI the default.
What do you think?

**Phase 1. Switch default UI**
* Promote Preview UI to default:
  * `/ui/preview` -> `/ui`
  * `/ui` -> `/ui/classic`
* This allow switching between new Web UI and Classic UI.
* Respect config: if `web-ui.preview.enabled=false` is explicitly set, `/ui` serves classic UI.
* Keep redirects working for existing links.
* Update documentation at [Web UI](https://trino.io/docs/current/admin/web-interface.html#) and [Preview UI](https://trino.io/docs/current/admin/preview-web-interface.html) sections to assume the new UI as default.

Call out the change clearly in release notes.

**Phase 2. Feedback period**
Collect feedback for at least one release cycle as it'll reach more users:
* Track and fix issues in https://github.com/trinodb/trino/issues/26724
* Decide whether to remove the Classic UI based on:
  * No open issues
  * Feature parity is good enough
  * No strong user pushback

**Phase 3. Remove Classic UI**
* Remove `/ui/classic` and all related code.
* Remove `web-ui.preview.enabled` config
* Delete Classic UI docs.
