### ISSUE TITLE
Continuous Integration testing of AWS-related functionalities

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#274]
The following Presto functions should be covered with continuous testing:

* [x] S3 regular reads and writes (https://github.com/prestosql/presto/pull/2371)
   - scripting support already available in https://github.com/prestosql/presto/blob/6c4a28dab8608bbf285e8d2bca57fb3ba690798f/.travis.yml#L178-L183
   - there needs to be some S3 bucket dedicated for testing, and access key pair provided as secret tokens in Travis
* [x] S3 Select (https://github.com/prestosql/presto/pull/2371)
   - most likely will be done together with "S3 regular reads and writes"
* [x] AWS Glue integration (https://github.com/prestosql/presto/pull/2806)
   - scripting support already available in https://github.com/prestosql/presto/blob/6c4a28dab8608bbf285e8d2bca57fb3ba690798f/.travis.yml#L186-L189
   - there needs to be an access key pair provided as secret tokens in Travis (if this is the same access key as for S3 tests, it's easier)
* [x] Redshift connector (https://github.com/prestosql/presto/issues/497)

Note:
this issue is just to capture the plan and track execution. Details are being hammered out on Slack, `#aws-test-infra`.

**Comment by hashhar** [comment]
seems we did all the work here already.

Only Kinesis connector is the remaining AWS component that doesn't get integration-tested. I'm not sure if it's worth carrying the connector or investing efforts there.
