### ISSUE TITLE
Aggregation pushdown

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#6613]
( This is a sub-issue of #18 ) 

- [x] SPI and engine changes for aggregation pushdown #3697
- [x]  base-JDBC support for aggregation pushdown (#3881)
- [x] Eliminate pushed down filters in JDBC connectors #4111
- [ ] Fix aggregation function alias pushdown #6189
- [x] Allow predicate pushdown after aggregation pushdown in JDBC connectors #4112
- [x]  aggregation pushdown in PostgreSQL (#3881)
  - [ ] Incorrect aggregation result when grouping by PostgreSQL TIME in presence of 24:00:00 values #5339
- [ ] aggregation pushdown in MySQL (#4138)
- [ ] aggregation pushdown in SQL Server (#4139, #5241)
- [ ] aggregation pushdown in Redshift
- [ ] aggregation pushdown in Druid (#4109)
- [ ] aggregation pushdown in Pinot (#4140)
- ...

**Comment by findepi** [comment]
Trino now has Aggregation pushdown for some time now. Of course there are follow-up issues, as always, and these are tracked separately.
This roadmap issue is not being kept up to date as a way to organize future work on the feature.

Good job, everyone involved. 👏
