### ISSUE TITLE
Improve SQL UPDATE support

### ISSUE THREAD

**Issue by djsstarburst** [trinodb/trino#6775]
#5861 added support for SQL UPDATE in the Trino engine and Hive connector, but with significant constraints, the most important of which is that update of partition or bucket columns was prohibited.  This ticket is opened to track improvement that could be made to SQL UPDATE support in the engine and Hive connector.

- [ ] Support SQL UPDATE of partition and bucket columns in the Trino engine #6772
- [ ] Support SQL UPDATE of partition and bucket columns in the Hive connector #6773
- [ ] SQL UPDATE - - update table and partition statistics in the Hive connector #6774

**Comment by findepi** [comment]
Thanks @djsstarburst for making the checklist. 
I have copied it into https://github.com/trinodb/trino/issues/3325 and so let's keep that issue as the source of truth for UPDATE work updates (sic!).
