### ISSUE TITLE
Migrate continuous integration builds from Travis to GitHub Actions (GHA)

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#6859]
- [x] Port main CI build for the `trino` repository
- [x] Port docker-images test automation from travis to GHA #5839
- [x] Migrate Tempto to GitHub Actions #5256
- [x] Migrate ORC protobuf from Travis to GitHub Actions #6860
- [x] #10849
- [x] #10850
- [x] #10851

Generally this involves the following steps

1. see how a simple GHA workflow looks like https://github.com/airlift/slice/pull/123
2. a maintainer needs to add a stub file in the `master` branch, otherwise GitHub won't run CI workflow on the PR
3. PR to be created with appropriate workflow -- starting with https://github.com/airlift/slice/pull/123 and taking into account how the .travis.yml looks like
   -  the PR should also remove `.travis.yml` file

**Comment by ivanfrias** [comment]
@findepi I am interested in trying to do this. Can you please assign it to me ?

**Comment by ebyhr** [comment]
Closing as all tasks are complete.
