### ISSUE TITLE
ClickHouse connector

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#7103]
- [ ] Create connector for ClickHouse #4500
- [ ] Map ClickHouse UUID to Trino UUID #7097 
- [ ] Map ClickHouse IPv4 and IPv6 to Trino IPADDRESS #7098
- [ ] Improve String, FixedString mapping in ClickHouse connector #7102
- [ ] Document ClickHouse connector type mapping #7099
- [ ] More predicate pushdown in ClickHouse connector #7100
- [ ] Fix disabled tests in ClickHouse connector #7101

**Comment by findepi** [comment]
cc @wgzhao

**Comment by PChou** [comment]
Is this connector planned to be implemented based on jdbc?

**Comment by findepi** [comment]
Yes, see https://github.com/trinodb/trino/pull/4909

**Comment by PChou** [comment]
@findepi perfect! That's what we really want!

**Comment by wgzhao** [comment]
@findepi  please add  #7130 into TODO List

**Comment by wgzhao** [comment]
* [x] Support for create table with MergeTree engine in in ClickHouse connector PR #7135

**Comment by hashhar** [comment]
Aggregation pushdown now merged in https://github.com/trinodb/trino/pull/7434.

**Comment by wgzhao** [comment]
* [x] Map ClickHouse UUID to Trino UUID #7915

**Comment by sondn98** [comment]
Should we have a fault-tolerant support for this connector?

**Comment by serg-kovalev** [comment]
> Should we have a fault-tolerant support for this connector?

Are there any plans to have a fault-tolerant support for ClickHouse connector?
