### ISSUE TITLE
MERGE statement

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#7708]
- [x] MERGE support in parser (https://github.com/trinodb/trino/pull/7126)
- [ ] MERGE support in analyzer, query planner, execution
- [ ] documentation
- connectors (can be split into follow up issues)
  - [ ] Hive for ORC ACID tables
  - [ ] Iceberg
  - [ ] Kudu

Relates to https://github.com/trinodb/trino/issues/3325

**Comment by findepi** [comment]
cc @djsstarburst @electrum @martint @losipiuk
