### ISSUE TITLE
Support Failure Recovery

### ISSUE THREAD

**Issue by arhimondr** [trinodb/trino#9101]
This issue is a parent issue for failure recovery support in Trino

High level design document (open for commenting): https://docs.google.com/document/d/18QQy8dkZQDNiBPEe3bsyt3RhImCKye4fUJB8bvoeLBI

**Full Query Retries**

- [x] Introduce task attempt concept: https://github.com/trinodb/trino/pull/9361
- [x] Implement de-duplication buffer: https://github.com/trinodb/trino/pull/9361
- [x] Refactor SqlStageExecution to support task re-scheduling: https://github.com/trinodb/trino/pull/9361
- [x] Refactor SqlQueryScheduler to support full query retries: https://github.com/trinodb/trino/pull/9361
- [x] Implement failure injection based integration tests for failure recovery: https://github.com/trinodb/trino/pull/9361
- [x] Remove de-duplication buffer capacity limitations to support failure recovery for queries with large output data set: https://github.com/trinodb/trino/pull/10507
- [x] https://github.com/trinodb/trino/issues/9934
- [x] Original failure cause sometimes lost with query retries: https://github.com/trinodb/trino/issues/10395

**Task Level Retries**

- [x] Introduce external exchange interface https://github.com/trinodb/trino/pull/9818
- [x] Support task level retries in de-duplication buffer https://github.com/trinodb/trino/pull/9818
- [x] Implement fault tolerant scheduler https://github.com/trinodb/trino/pull/9818
- [x] Implement weight based split assignment https://github.com/trinodb/trino/pull/10837
- [x] Implement adaptive task sizing for intermediate stages https://github.com/trinodb/trino/pull/11023
- [x] Account memory retained by splits on coordinator https://github.com/trinodb/trino/pull/10877
- [ ] https://github.com/trinodb/trino/issues/9935 
- [x] Optimize Page serialization for external exchange (https://github.com/trinodb/trino/pull/10241)
- [x] https://github.com/trinodb/trino/issues/9936
- [x] https://github.com/trinodb/trino/issues/11050
- [x] Run memory intensive tasks on a dedicated node (https://github.com/trinodb/trino/pull/10432)
- [x] https://github.com/trinodb/trino/issues/11051
- [x] #10808
- [x] #11020
- [ ] Remove memory limitations for split enumeration

**Reporting and UI**

- [x] #10734
- [x] #11959

**Connectors support**

Ensure DML operations in connectors follow Trino commit semantics and don't produce unwanted side effects

- [x] https://github.com/trinodb/trino/issues/10252
- [x] https://github.com/trinodb/trino/issues/10253
- [ ] https://github.com/trinodb/trino/issues/10254
- [x] https://github.com/trinodb/trino/issues/11591
- [ ] ...

**Backlog**

- [ ] Extend error code with "retriable" field. Mark existing errors accordingly.

**Comment by arhimondr** [comment]
### Project Milestones (Draft)

## Milestone 1

**Deliver “whole query retries”**

Whole query retries should provide a simple failure recovery mechanism for short running queries. The idea is to retry the whole query in case of a failure transparently to the user. For queries that take several seconds to minutes the latency hit of the whole query retry should be within normal dispersion and still significantly improve perceived user experience.

To achieve this milestone the next challenges must be solved:

- [ ] Task atomicity
  - [ ] Introduce commit protocol for table write
  - [ ] Add de-duplication buffer on coordinator
- [ ] Restartable tasks
  - [ ] Introduce task attempt concept

## Milestone 2

**Deliver task level failure recovery for small clusters (<10-20 nodes)**

At this step task level failure recovery will be supported. Task failure will no longer cause a query failure and tasks will be restarted independently in an event of a failure. Intermediate data will be stored directly in S3 in a naive way without any extra optimizations. High cardinality shuffles (thus large clusters) wouldn’t be supported.

To achieve this milestone the next challenges must be solved:

- [ ] Deterministic tasks
  - [ ] Implement deterministic split assignment
  - [ ]  Implement deterministic partitioning
- [ ] Provide shuffle service interface
  - [ ] Implement simple S3 based shuffle implementation
- [ ] Implement batch query scheduler
  - [ ] Implement iterative task scheduling, retries and speculative execution (start with full stage barrier scheduling)

Recoverable mode at this step will be an opt-in based decision.

At this step we can also start working on adaptive query execution.

## Milestone 3

**Deliver fine grained failure recovery for clusters of any size**

At this step a more efficient, high cardinality shuffle must be supported.

To achieve this milestone the next challenges must be solved:

- [ ] Improve shuffle scalability
- [ ] AND / OR Integrate with shuffle services available in popular cloud providers

At this step we may start improving the scheduler to support parallel execution of multiple interconnected stages.

## Milestone 4

**Deliver support for high memory queries**

Partitioning mechanisms and shuffle service must be scalable enough to support partitioning cardinallity that is significantly higher than the maximum supported cluster size.

To achieve this milestone the next challenges must be solved:

- [ ] Support high cardinality partitioning
- [ ] Resolve small files problem

## Milestone 5

**System can automatically adapt to workload**

At this step the decision to employ recoverable mode must no longer be opted in and must be done automatically. System should be smart enough to optimally choose the number of partitions, handle skews and automatically fix suboptimal planner decisions

To achieve this milestone the next challenges must be solved:

- [ ] Improve spilling capabilities
   - [ ] Implement spilling to DFS (such as S3)
   - [ ] Improve spilling coverage
       - [ ] Implement Distinct / Order By accumulators spilling
       - [ ] Implement Right Join / Single Key Skewed Join spilling
- [ ] Implement required adaptive query optimizations
    - [ ] Partition coalescing (to automate partitioning decision making)
    - [ ] Join optimizations
        - [ ] Implement adaptive join skew handling
        - [ ] Implement adaptive join type selection
        - [ ] Implement adaptive join side swapping

**Comment by findepi** [comment]
Closing in favor of https://github.com/trinodb/trino/issues/2909

**Comment by arhimondr** [comment]
https://trino.io/blog/2022/05/05/tardigrade-launch.html
